import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { TopNavBar } from './components/topNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {


  return (
    <html className='h-full' lang="en">
      <body className='bg-stone-100 h-full'>
        <div className='flex w-full flex-col'>
          <TopNavBar />
          <div className='grow'>
            {props.children}
            <div className=' grid grid-cols-1 gap-8 p-6 md:px-20 md:grid-cols-2 md:gap-6 lg:px-40 w-full'>
              
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
