import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='h-full' lang="en">
      <body className='bg-stone-100 h-full'>
        <div className='flex w-full flex-col'>
          <div className=' border z-50 p-3'>
            <p className='text-4xl '>Header</p>
          </div>
          <div className='grow'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
