import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { TopNavBar } from './components/topNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html className='h-full' lang="en">
      <body className='bg-stone-100 h-full'>
        <div className='flex w-full flex-col'>
          <TopNavBar/>
          <div className='grow'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
